// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.10.0
// source: blockwindowsyncer/types.go

package blockwindowsyncer

import (
	"io"
	"sync/atomic"
	"unicode/utf8"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Int64

	_ = io.ErrUnexpectedEOF
	_ = utf8.ValidString
)

const (
	canoto__BlockFetchRequest__BlockHeight__tag  = "\x08" // canoto.Tag(1, canoto.Varint)
	canoto__BlockFetchRequest__MinTimestamp__tag = "\x10" // canoto.Tag(2, canoto.Varint)
)

type canotoData_BlockFetchRequest struct {
	// Enforce noCopy before atomic usage.
	// See https://github.com/StephenButtolph/canoto/pull/32
	_ atomic.Int64

	size int
}

// MakeCanoto creates a new empty value.
func (*BlockFetchRequest) MakeCanoto() *BlockFetchRequest {
	return new(BlockFetchRequest)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
func (c *BlockFetchRequest) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
//
// This function enables configuration of reader options.
func (c *BlockFetchRequest) UnmarshalCanotoFrom(r canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadInt(&r, &c.BlockHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.BlockHeight) {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadInt(&r, &c.MinTimestamp); err != nil {
				return err
			}
			if canoto.IsZero(c.MinTimestamp) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *BlockFetchRequest) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to call this function concurrently.
func (c *BlockFetchRequest) CalculateCanotoCache() {
	if c == nil {
		return
	}
	c.canotoData_BlockFetchRequest.size = 0
	if !canoto.IsZero(c.BlockHeight) {
		c.canotoData_BlockFetchRequest.size += len(canoto__BlockFetchRequest__BlockHeight__tag) + canoto.SizeInt(c.BlockHeight)
	}
	if !canoto.IsZero(c.MinTimestamp) {
		c.canotoData_BlockFetchRequest.size += len(canoto__BlockFetchRequest__MinTimestamp__tag) + canoto.SizeInt(c.MinTimestamp)
	}
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *BlockFetchRequest) CachedCanotoSize() int {
	if c == nil {
		return 0
	}
	return c.canotoData_BlockFetchRequest.size
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *BlockFetchRequest) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *BlockFetchRequest) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.BlockHeight) {
		canoto.Append(&w, canoto__BlockFetchRequest__BlockHeight__tag)
		canoto.AppendInt(&w, c.BlockHeight)
	}
	if !canoto.IsZero(c.MinTimestamp) {
		canoto.Append(&w, canoto__BlockFetchRequest__MinTimestamp__tag)
		canoto.AppendInt(&w, c.MinTimestamp)
	}
	return w
}

const (
	canoto__BlockFetchResponse__Blocks__tag = "\x0a" // canoto.Tag(1, canoto.Len)
)

type canotoData_BlockFetchResponse struct {
	// Enforce noCopy before atomic usage.
	// See https://github.com/StephenButtolph/canoto/pull/32
	_ atomic.Int64

	size int
}

// MakeCanoto creates a new empty value.
func (*BlockFetchResponse) MakeCanoto() *BlockFetchResponse {
	return new(BlockFetchResponse)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
func (c *BlockFetchResponse) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
//
// This function enables configuration of reader options.
func (c *BlockFetchResponse) UnmarshalCanotoFrom(r canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			remainingBytes := r.B
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			err := canoto.ReadBytes(&r, new([]byte))
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}

			count, err := canoto.CountBytes(r.B, canoto__BlockFetchResponse__Blocks__tag)
			if err != nil {
				return err
			}
			c.Blocks = canoto.MakeSlice(c.Blocks, 1+count)

			r.B = remainingBytes
			if err := canoto.ReadBytes(&r, &c.Blocks[0]); err != nil {
				return err
			}
			for i := range count {
				r.B = r.B[len(canoto__BlockFetchResponse__Blocks__tag):]
				if err := canoto.ReadBytes(&r, &c.Blocks[1+i]); err != nil {
					return err
				}
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *BlockFetchResponse) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to call this function concurrently.
func (c *BlockFetchResponse) CalculateCanotoCache() {
	if c == nil {
		return
	}
	c.canotoData_BlockFetchResponse.size = 0
	for _, v := range c.Blocks {
		c.canotoData_BlockFetchResponse.size += len(canoto__BlockFetchResponse__Blocks__tag) + canoto.SizeBytes(v)
	}
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *BlockFetchResponse) CachedCanotoSize() int {
	if c == nil {
		return 0
	}
	return c.canotoData_BlockFetchResponse.size
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *BlockFetchResponse) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *BlockFetchResponse) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	for _, v := range c.Blocks {
		canoto.Append(&w, canoto__BlockFetchResponse__Blocks__tag)
		canoto.AppendBytes(&w, v)
	}
	return w
}
