// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAccountStats():Promise<Array<main.GenericInfo>>;

export function GetChainID():Promise<string>;

export function GetLatestBlocks():Promise<Array<main.BlockInfo>>;

export function GetTransactionStats():Promise<Array<main.GenericInfo>>;

export function GetUnitPrices():Promise<Array<main.GenericInfo>>;
