// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChainID() {
  return window['go']['main']['App']['GetChainID']();
}

export function GetLatestBlocks() {
  return window['go']['main']['App']['GetLatestBlocks']();
}
