// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChains() {
  return window['go']['main']['App']['GetChains']();
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}
