// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChains():Promise<Array<string>>;

export function GetKeys():Promise<Array<string>>;
