[package]
name = "sdk_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
wasmlanche_sdk = { version = "0.1.0", path = "../wasmlanche_sdk" }

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = { version = "2.0.37", features = ["full"] }
