version: "2"
run:
  timeout: 10m
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dupword
    - errcheck
    - errorlint
    - forbidigo
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - spancheck
    - staticcheck
    - tagalign
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    depguard:
      rules:
        packages:
          deny:
            - pkg: container/list
              desc: github.com/ava-labs/avalanchego/utils/linked should be used instead.
            - pkg: github.com/stretchr/testify/assert
              desc: github.com/stretchr/testify/require should be used instead.
            - pkg: io/ioutil
              desc: io/ioutil is deprecated. Use package io or os instead.
    errorlint:
      asserts: false
      comparison: false
    forbidigo:
      forbid:
        - pattern: require\.Error$(# ErrorIs should be used instead)?
        - pattern: require\.ErrorContains$(# ErrorIs should be used instead)?
        - pattern: require\.EqualValues$(# Equal should be used instead)?
        - pattern: require\.NotEqualValues$(# NotEqual should be used instead)?
        - pattern: ^(t|b|tb|f)\.(Fatal|Fatalf|Error|Errorf)$(# the require library should be used instead)?
    gosec:
      excludes:
        - G107
        - G115
    importas:
      alias:
        - pkg: github.com/ava-labs/avalanchego/utils/math
          alias: safemath
        - pkg: github.com/ava-labs/avalanchego/utils
          alias: avautils
        - pkg: github.com/ava-labs/avalanchego/trace
          alias: avatrace
        - pkg: github.com/ava-labs/avalanchego/api/metrics
          alias: avametrics
        - pkg: github.com/ava-labs/avalanchego/cache
          alias: avacache
        - pkg: github.com/ava-labs/avalanchego/x/sync
          alias: avasync
      no-unaliased: false
      no-extra-aliases: false
    revive:
      rules:
        - name: bool-literal-in-expr
          disabled: false
        - name: early-return
          disabled: false
        - name: empty-lines
          disabled: false
        - name: string-format
          arguments:
            - - b.Logf[0]
              - /.*%.*/
              - no format directive, use b.Log instead
            - - fmt.Errorf[0]
              - /.*%.*/
              - no format directive, use errors.New instead
            - - fmt.Fprintf[1]
              - /.*%.*/
              - no format directive, use fmt.Fprint instead
            - - fmt.Printf[0]
              - /.*%.*/
              - no format directive, use fmt.Print instead
            - - fmt.Sprintf[0]
              - /.*%.*/
              - no format directive, use fmt.Sprint instead
            - - log.Fatalf[0]
              - /.*%.*/
              - no format directive, use log.Fatal instead
            - - log.Printf[0]
              - /.*%.*/
              - no format directive, use log.Print instead
            - - t.Logf[0]
              - /.*%.*/
              - no format directive, use t.Log instead
          disabled: false
        - name: struct-tag
          disabled: false
        - name: unexported-naming
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt\.Fprint
            - fmt\.Fprintf
            - fmt\.Fprintln
            - fmt\.Print
            - fmt\.Printf
            - fmt\.Println
            - math/rand\.Read
            - strings\.Builder\.WriteString
          disabled: false
        - name: unused-parameter
          disabled: false
        - name: unused-receiver
          disabled: false
        - name: useless-break
          disabled: false
    spancheck:
      checks:
        - end
    staticcheck:
      checks:
        - all
        - "-SA1019"
        - "-SA6002"
        - "-QF1008"
    tagalign:
      align: true
      sort: true
      order:
        - serialize
      strict: true
    testifylint:
      enable-all: true
      disable:
        - go-require
        - float-compare
        - equal-values
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/ava-labs/hypersdk)
        - alias
      custom-order: true
  exclusions:
    generated: lax
