# Base directory for the whole execution.
baseDir = "."

# Path to the header template file.
# The header template file is skipped on any execution.
headerPath = "license-header"

# On enabled, check the license header matches exactly with whitespace.
strictCheck = true

# Patterns of path to be included on execution.
includes = ["**/*.rs", "**/*.go"]

# exclude all mock_*.go files
excludes = ["**/mock_*.go"]

# Whether you use the default mapping.
useDefaultMapping = true

# Properties to fulfill the template.
[properties]
Year = 2024
