# Base directory for the whole execution.
baseDir = "."

# Path to the header template file.
# The header template file is skipped on any execution.
headerPath = "license-header.txt"

# On enabled, check the license header matches exactly with whitespace.
strictCheck = true

# Patterns of path to be included on execution.
includes = ["**/*.rs", "**/*.go"]

# Whether you use the default mapping.
useDefaultMapping = true

additionalHeaders = ["license-style.txt"]

[mapping.GO_STYLE]
extensions = ["go"]
