FROM node:20-bookworm AS builder

WORKDIR /web

COPY examples/morpheusvm/frontend/web_wallet /web

RUN --mount=type=cache,target=/root/.npm \
    npm ci
RUN CI=yes npm run test
RUN npm run build

FROM nginx:1.27

COPY --from=builder /web/dist /usr/share/nginx/html