// Copyright (C) 2024, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/hypersdk/vm (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -package=vm -destination=vm/mock_interface.go github.com/ava-labs/hypersdk/vm Interface
//

// Package vm is a generated GoMock package.
package vm

import (
	context "context"
	reflect "reflect"

	metrics "github.com/ava-labs/avalanchego/api/metrics"
	snow "github.com/ava-labs/avalanchego/snow"
	builder "github.com/ava-labs/hypersdk/builder"
	chain "github.com/ava-labs/hypersdk/chain"
	gossiper "github.com/ava-labs/hypersdk/gossiper"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Accepted mocks base method.
func (m *MockInterface) Accepted(arg0 context.Context, arg1 *chain.StatelessBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accepted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Accepted indicates an expected call of Accepted.
func (mr *MockInterfaceMockRecorder) Accepted(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accepted", reflect.TypeOf((*MockInterface)(nil).Accepted), arg0, arg1)
}

// Initialize mocks base method.
func (m *MockInterface) Initialize(arg0 *VM, arg1 *snow.Context, arg2 metrics.MultiGatherer, arg3, arg4, arg5 []byte) (Config, Genesis, builder.Builder, gossiper.Gossiper, Handlers, chain.ActionRegistry, chain.AuthRegistry, map[byte]AuthEngine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(Config)
	ret1, _ := ret[1].(Genesis)
	ret2, _ := ret[2].(builder.Builder)
	ret3, _ := ret[3].(gossiper.Gossiper)
	ret4, _ := ret[4].(Handlers)
	ret5, _ := ret[5].(chain.ActionRegistry)
	ret6, _ := ret[6].(chain.AuthRegistry)
	ret7, _ := ret[7].(map[byte]AuthEngine)
	ret8, _ := ret[8].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8
}

// Initialize indicates an expected call of Initialize.
func (mr *MockInterfaceMockRecorder) Initialize(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockInterface)(nil).Initialize), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Rules mocks base method.
func (m *MockInterface) Rules(arg0 int64) chain.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", arg0)
	ret0, _ := ret[0].(chain.Rules)
	return ret0
}

// Rules indicates an expected call of Rules.
func (mr *MockInterfaceMockRecorder) Rules(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockInterface)(nil).Rules), arg0)
}

// Shutdown mocks base method.
func (m *MockInterface) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockInterfaceMockRecorder) Shutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockInterface)(nil).Shutdown), arg0)
}

// StateManager mocks base method.
func (m *MockInterface) StateManager() chain.StateManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateManager")
	ret0, _ := ret[0].(chain.StateManager)
	return ret0
}

// StateManager indicates an expected call of StateManager.
func (mr *MockInterfaceMockRecorder) StateManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateManager", reflect.TypeOf((*MockInterface)(nil).StateManager))
}
