// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.10.0
// source: chain/types/transaction.go

package types

import (
	"io"
	"sync/atomic"
	"unicode/utf8"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Int64

	_ = io.ErrUnexpectedEOF
	_ = utf8.ValidString
)

const (
	canoto__TransactionData__Expiry__tag  = "\x08" // canoto.Tag(1, canoto.Varint)
	canoto__TransactionData__ChainID__tag = "\x12" // canoto.Tag(2, canoto.Len)
	canoto__TransactionData__MaxFee__tag  = "\x19" // canoto.Tag(3, canoto.I64)
	canoto__TransactionData__Actions__tag = "\x22" // canoto.Tag(4, canoto.Len)
)

type canotoData_TransactionData struct {
	// Enforce noCopy before atomic usage.
	// See https://github.com/StephenButtolph/canoto/pull/32
	_ atomic.Int64

	size int
}

// MakeCanoto creates a new empty value.
func (*TransactionData[T1]) MakeCanoto() *TransactionData[T1] {
	return new(TransactionData[T1])
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
func (c *TransactionData[T1]) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
//
// This function enables configuration of reader options.
func (c *TransactionData[T1]) UnmarshalCanotoFrom(r canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadSint(&r, &c.Expiry); err != nil {
				return err
			}
			if canoto.IsZero(c.Expiry) {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			var length int64
			if err := canoto.ReadInt(&r, &length); err != nil {
				return err
			}

			const (
				expectedLength      = len(c.ChainID)
				expectedLengthInt64 = int64(expectedLength)
			)
			if length != expectedLengthInt64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy(c.ChainID[:], r.B)
			if canoto.IsZero(c.ChainID) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 3:
			if wireType != canoto.I64 {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadFint64(&r, &c.MaxFee); err != nil {
				return err
			}
			if canoto.IsZero(c.MaxFee) {
				return canoto.ErrZeroValue
			}
		case 4:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			err := canoto.ReadBytes(&r, &msgBytes)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}

			remainingBytes := r.B
			count, err := canoto.CountBytes(remainingBytes, canoto__TransactionData__Actions__tag)
			if err != nil {
				return err
			}

			c.Actions = canoto.MakeSlice(c.Actions, 1+count)
			if len(msgBytes) != 0 {
				r.B = msgBytes
				c.Actions[0] = c.Actions[0].MakeCanoto()
				err = c.Actions[0].UnmarshalCanotoFrom(r)
				r.B = remainingBytes
				if err != nil {
					return err
				}
			}

			for i := range count {
				r.B = r.B[len(canoto__TransactionData__Actions__tag):]
				r.Unsafe = true
				err := canoto.ReadBytes(&r, &msgBytes)
				r.Unsafe = originalUnsafe
				if err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}

				remainingBytes := r.B
				r.B = msgBytes
				c.Actions[1+i] = c.Actions[1+i].MakeCanoto()
				err = c.Actions[1+i].UnmarshalCanotoFrom(r)
				r.B = remainingBytes
				if err != nil {
					return err
				}
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *TransactionData[T1]) ValidCanoto() bool {
	if c == nil {
		return true
	}
	for i := range c.Actions {
		if !c.Actions[i].ValidCanoto() {
			return false
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to call this function concurrently.
func (c *TransactionData[T1]) CalculateCanotoCache() {
	if c == nil {
		return
	}
	c.canotoData.size = 0
	if !canoto.IsZero(c.Expiry) {
		c.canotoData.size += len(canoto__TransactionData__Expiry__tag) + canoto.SizeSint(c.Expiry)
	}
	if !canoto.IsZero(c.ChainID) {
		c.canotoData.size += len(canoto__TransactionData__ChainID__tag) + canoto.SizeBytes(c.ChainID[:])
	}
	if !canoto.IsZero(c.MaxFee) {
		c.canotoData.size += len(canoto__TransactionData__MaxFee__tag) + canoto.SizeFint64
	}
	for i := range c.Actions {
		c.Actions[i].CalculateCanotoCache()
		fieldSize := c.Actions[i].CachedCanotoSize()
		c.canotoData.size += len(canoto__TransactionData__Actions__tag) + canoto.SizeInt(int64(fieldSize)) + fieldSize
	}
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *TransactionData[T1]) CachedCanotoSize() int {
	if c == nil {
		return 0
	}
	return c.canotoData.size
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *TransactionData[T1]) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *TransactionData[T1]) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.Expiry) {
		canoto.Append(&w, canoto__TransactionData__Expiry__tag)
		canoto.AppendSint(&w, c.Expiry)
	}
	if !canoto.IsZero(c.ChainID) {
		canoto.Append(&w, canoto__TransactionData__ChainID__tag)
		canoto.AppendBytes(&w, c.ChainID[:])
	}
	if !canoto.IsZero(c.MaxFee) {
		canoto.Append(&w, canoto__TransactionData__MaxFee__tag)
		canoto.AppendFint64(&w, c.MaxFee)
	}
	for i := range c.Actions {
		canoto.Append(&w, canoto__TransactionData__Actions__tag)
		fieldSize := c.Actions[i].CachedCanotoSize()
		canoto.AppendInt(&w, int64(fieldSize))
		if fieldSize != 0 {
			w = c.Actions[i].MarshalCanotoInto(w)
		}
	}
	return w
}

const (
	canoto__Transaction__TransactionData__tag = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__Transaction__Auth__tag            = "\x12" // canoto.Tag(2, canoto.Len)
)

type canotoData_Transaction struct {
	// Enforce noCopy before atomic usage.
	// See https://github.com/StephenButtolph/canoto/pull/32
	_ atomic.Int64

	size int
}

// MakeCanoto creates a new empty value.
func (*Transaction[T1, T2]) MakeCanoto() *Transaction[T1, T2] {
	return new(Transaction[T1, T2])
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
func (c *Transaction[T1, T2]) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
//
// This function enables configuration of reader options.
func (c *Transaction[T1, T2]) UnmarshalCanotoFrom(r canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			err := canoto.ReadBytes(&r, &msgBytes)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}

			remainingBytes := r.B
			r.B = msgBytes
			c.TransactionData = c.TransactionData.MakeCanoto()
			err = c.TransactionData.UnmarshalCanotoFrom(r)
			r.B = remainingBytes
			if err != nil {
				return err
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			err := canoto.ReadBytes(&r, &msgBytes)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}

			remainingBytes := r.B
			r.B = msgBytes
			c.Auth = c.Auth.MakeCanoto()
			err = c.Auth.UnmarshalCanotoFrom(r)
			r.B = remainingBytes
			if err != nil {
				return err
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Transaction[T1, T2]) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !c.TransactionData.ValidCanoto() {
		return false
	}
	if !c.Auth.ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to call this function concurrently.
func (c *Transaction[T1, T2]) CalculateCanotoCache() {
	if c == nil {
		return
	}
	c.canotoData.size = 0
	c.TransactionData.CalculateCanotoCache()
	if fieldSize := c.TransactionData.CachedCanotoSize(); fieldSize != 0 {
		c.canotoData.size += len(canoto__Transaction__TransactionData__tag) + canoto.SizeInt(int64(fieldSize)) + fieldSize
	}
	c.Auth.CalculateCanotoCache()
	if fieldSize := c.Auth.CachedCanotoSize(); fieldSize != 0 {
		c.canotoData.size += len(canoto__Transaction__Auth__tag) + canoto.SizeInt(int64(fieldSize)) + fieldSize
	}
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Transaction[T1, T2]) CachedCanotoSize() int {
	if c == nil {
		return 0
	}
	return c.canotoData.size
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *Transaction[T1, T2]) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *Transaction[T1, T2]) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if fieldSize := c.TransactionData.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__Transaction__TransactionData__tag)
		canoto.AppendInt(&w, int64(fieldSize))
		w = c.TransactionData.MarshalCanotoInto(w)
	}
	if fieldSize := c.Auth.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__Transaction__Auth__tag)
		canoto.AppendInt(&w, int64(fieldSize))
		w = c.Auth.MarshalCanotoInto(w)
	}
	return w
}
