// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAddressBook(arg1, arg2) {
  return window['go']['main']['App']['AddAddressBook'](arg1, arg2);
}

export function AddAsset(arg1) {
  return window['go']['main']['App']['AddAsset'](arg1);
}

export function CloseOrder(arg1, arg2) {
  return window['go']['main']['App']['CloseOrder'](arg1, arg2);
}

export function CreateAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAsset'](arg1, arg2, arg3);
}

export function CreateOrder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateOrder'](arg1, arg2, arg3, arg4, arg5);
}

export function FillOrder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FillOrder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAccountStats() {
  return window['go']['main']['App']['GetAccountStats']();
}

export function GetAddress() {
  return window['go']['main']['App']['GetAddress']();
}

export function GetAddressBook() {
  return window['go']['main']['App']['GetAddressBook']();
}

export function GetAllAssets() {
  return window['go']['main']['App']['GetAllAssets']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetChainID() {
  return window['go']['main']['App']['GetChainID']();
}

export function GetCommitHash() {
  return window['go']['main']['App']['GetCommitHash']();
}

export function GetFaucetSolutions() {
  return window['go']['main']['App']['GetFaucetSolutions']();
}

export function GetFeed() {
  return window['go']['main']['App']['GetFeed']();
}

export function GetFeedInfo() {
  return window['go']['main']['App']['GetFeedInfo']();
}

export function GetLatestBlocks() {
  return window['go']['main']['App']['GetLatestBlocks']();
}

export function GetMyAssets() {
  return window['go']['main']['App']['GetMyAssets']();
}

export function GetMyOrders() {
  return window['go']['main']['App']['GetMyOrders']();
}

export function GetOrders(arg1) {
  return window['go']['main']['App']['GetOrders'](arg1);
}

export function GetTransactionStats() {
  return window['go']['main']['App']['GetTransactionStats']();
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}

export function GetUnitPrices() {
  return window['go']['main']['App']['GetUnitPrices']();
}

export function Message(arg1, arg2) {
  return window['go']['main']['App']['Message'](arg1, arg2);
}

export function MintAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['MintAsset'](arg1, arg2, arg3);
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function StartFaucetSearch() {
  return window['go']['main']['App']['StartFaucetSearch']();
}

export function Transfer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Transfer'](arg1, arg2, arg3, arg4);
}
