// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.15.0
// source: bls.go

package auth

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__BLS__SignerBytes__tag    = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__BLS__SignatureBytes__tag = "\x12" // canoto.Tag(2, canoto.Len)
)

type canotoData_BLS struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*BLS) CanotoSpec(...reflect.Type) *canoto.Spec {
	s := &canoto.Spec{
		Name: "BLS",
		Fields: []canoto.FieldType{
			{
				FieldNumber: 1,
				Name:        "SignerBytes",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: 2,
				Name:        "SignatureBytes",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*BLS) MakeCanoto() *BLS {
	return new(BLS)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *BLS) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *BLS) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = BLS{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.SignerBytes); err != nil {
				return err
			}
			if len(c.SignerBytes) == 0 {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.SignatureBytes); err != nil {
				return err
			}
			if len(c.SignatureBytes) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *BLS) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *BLS) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.SignerBytes) != 0 {
		size += uint64(len(canoto__BLS__SignerBytes__tag)) + canoto.SizeBytes(c.SignerBytes)
	}
	if len(c.SignatureBytes) != 0 {
		size += uint64(len(canoto__BLS__SignatureBytes__tag)) + canoto.SizeBytes(c.SignatureBytes)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *BLS) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *BLS) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *BLS) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.SignerBytes) != 0 {
		canoto.Append(&w, canoto__BLS__SignerBytes__tag)
		canoto.AppendBytes(&w, c.SignerBytes)
	}
	if len(c.SignatureBytes) != 0 {
		canoto.Append(&w, canoto__BLS__SignatureBytes__tag)
		canoto.AppendBytes(&w, c.SignatureBytes)
	}
	return w
}
