// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.15.0
// source: secp256r1.go

package auth

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__SECP256R1__Signer__tag    = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__SECP256R1__Signature__tag = "\x12" // canoto.Tag(2, canoto.Len)
)

type canotoData_SECP256R1 struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*SECP256R1) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero SECP256R1
	s := &canoto.Spec{
		Name: "SECP256R1",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    1,
				Name:           "Signer",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.Signer)),
			},
			{
				FieldNumber:    2,
				Name:           "Signature",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.Signature)),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*SECP256R1) MakeCanoto() *SECP256R1 {
	return new(SECP256R1)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *SECP256R1) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *SECP256R1) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = SECP256R1{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.Signer)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.Signer)[:], r.B)
			if canoto.IsZero(c.Signer) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.Signature)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.Signature)[:], r.B)
			if canoto.IsZero(c.Signature) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *SECP256R1) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *SECP256R1) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.Signer) {
		size += uint64(len(canoto__SECP256R1__Signer__tag)) + canoto.SizeBytes((&c.Signer)[:])
	}
	if !canoto.IsZero(c.Signature) {
		size += uint64(len(canoto__SECP256R1__Signature__tag)) + canoto.SizeBytes((&c.Signature)[:])
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *SECP256R1) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *SECP256R1) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *SECP256R1) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.Signer) {
		canoto.Append(&w, canoto__SECP256R1__Signer__tag)
		canoto.AppendBytes(&w, (&c.Signer)[:])
	}
	if !canoto.IsZero(c.Signature) {
		canoto.Append(&w, canoto__SECP256R1__Signature__tag)
		canoto.AppendBytes(&w, (&c.Signature)[:])
	}
	return w
}
