# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

version: '2.4'

services:
  # Default mmap count limits on most systems is too low resulting in memory exceptions.
  # ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
  db:
    image: ghcr.io/openzipkin/zipkin-elasticsearch7:latest
    container_name: elasticsearch

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      - JAVA_OPTS=-Xms128m -Xmx1024m -XX:+ExitOnOutOfMemoryError
      - ZIPKIN_UI_DEPENDENCY_ENABLED=false # not used by our application
    ports:
      - 9411:9411
    depends_on:
      - db
