// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.15.0
// source: transfer.go

package actions

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__Transfer__To__tag    = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__Transfer__Value__tag = "\x10" // canoto.Tag(2, canoto.Varint)
	canoto__Transfer__Memo__tag  = "\x1a" // canoto.Tag(3, canoto.Len)
)

type canotoData_Transfer struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Transfer) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero Transfer
	s := &canoto.Spec{
		Name: "Transfer",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    1,
				Name:           "To",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.To)),
			},
			{
				FieldNumber: 2,
				Name:        "Value",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Value),
			},
			{
				FieldNumber: 3,
				Name:        "Memo",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*Transfer) MakeCanoto() *Transfer {
	return new(Transfer)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Transfer) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Transfer) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = Transfer{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.To)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.To)[:], r.B)
			if canoto.IsZero(c.To) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 2:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Value); err != nil {
				return err
			}
			if canoto.IsZero(c.Value) {
				return canoto.ErrZeroValue
			}
		case 3:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Memo); err != nil {
				return err
			}
			if len(c.Memo) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Transfer) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *Transfer) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.To) {
		size += uint64(len(canoto__Transfer__To__tag)) + canoto.SizeBytes((&c.To)[:])
	}
	if !canoto.IsZero(c.Value) {
		size += uint64(len(canoto__Transfer__Value__tag)) + canoto.SizeUint(c.Value)
	}
	if len(c.Memo) != 0 {
		size += uint64(len(canoto__Transfer__Memo__tag)) + canoto.SizeBytes(c.Memo)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Transfer) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *Transfer) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *Transfer) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.To) {
		canoto.Append(&w, canoto__Transfer__To__tag)
		canoto.AppendBytes(&w, (&c.To)[:])
	}
	if !canoto.IsZero(c.Value) {
		canoto.Append(&w, canoto__Transfer__Value__tag)
		canoto.AppendUint(&w, c.Value)
	}
	if len(c.Memo) != 0 {
		canoto.Append(&w, canoto__Transfer__Memo__tag)
		canoto.AppendBytes(&w, c.Memo)
	}
	return w
}

const (
	canoto__TransferResult__SenderBalance__tag   = "\x08" // canoto.Tag(1, canoto.Varint)
	canoto__TransferResult__ReceiverBalance__tag = "\x10" // canoto.Tag(2, canoto.Varint)
)

type canotoData_TransferResult struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*TransferResult) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero TransferResult
	s := &canoto.Spec{
		Name: "TransferResult",
		Fields: []canoto.FieldType{
			{
				FieldNumber: 1,
				Name:        "SenderBalance",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.SenderBalance),
			},
			{
				FieldNumber: 2,
				Name:        "ReceiverBalance",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.ReceiverBalance),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*TransferResult) MakeCanoto() *TransferResult {
	return new(TransferResult)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *TransferResult) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *TransferResult) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = TransferResult{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.SenderBalance); err != nil {
				return err
			}
			if canoto.IsZero(c.SenderBalance) {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.ReceiverBalance); err != nil {
				return err
			}
			if canoto.IsZero(c.ReceiverBalance) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *TransferResult) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *TransferResult) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.SenderBalance) {
		size += uint64(len(canoto__TransferResult__SenderBalance__tag)) + canoto.SizeUint(c.SenderBalance)
	}
	if !canoto.IsZero(c.ReceiverBalance) {
		size += uint64(len(canoto__TransferResult__ReceiverBalance__tag)) + canoto.SizeUint(c.ReceiverBalance)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *TransferResult) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TransferResult) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TransferResult) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.SenderBalance) {
		canoto.Append(&w, canoto__TransferResult__SenderBalance__tag)
		canoto.AppendUint(&w, c.SenderBalance)
	}
	if !canoto.IsZero(c.ReceiverBalance) {
		canoto.Append(&w, canoto__TransferResult__ReceiverBalance__tag)
		canoto.AppendUint(&w, c.ReceiverBalance)
	}
	return w
}
