{
 "title": "Load Test Dashboard",
 "time": { "from": "2024-11-18T21:26:31.928Z", "to": "2024-11-18T21:35:44.907Z" },
 "templating": {
  "list": [
   {
    "name": "CHAIN_ID",
    "query": "QSRTAobzQCFvCGsQfxFdEEfskkoaxEJmrE5r1dJkaMYNiyKiG"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions (Cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "avalanche_QSRTAobzQCFvCGsQfxFdEEfskkoaxEJmrE5r1dJkaMYNiyKiG_vm_hypersdk_vm_txs_received",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Virtual Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avalanche_requests_average_latency",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job=~\"avalanchego-machine\"} - node_memory_MemFree_bytes{job=~\"avalanchego-machine\"} - node_memory_Buffers_bytes{job=~\"avalanchego-machine\"} - node_memory_Cached_bytes{job=~\"avalanchego-machine\"}) / node_memory_MemTotal_bytes{job=~\"avalanchego-machine\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanchego-machine\", mode=\"idle\"}[30s])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avalanche_go_goroutines", "legendFormat": "avalanchego: {{instance}}" },
    {
     "expr": "avalanche_${CHAIN_ID}_vm_go_goroutines",
     "legendFormat": "aizelvm: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Packets (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Packets (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=\"ens5\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Bandwidth (Write/Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Bandwidth (Write/Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total[60s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Ops (Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Disk Bandwidth (Read/Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Bandwidth (Read/Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total[60s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Ops (Read)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Disk I/O Now",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"iowait\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}