// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAddressBook(arg1:string,arg2:string):Promise<void>;

export function AddAsset(arg1:string):Promise<void>;

export function CreateAsset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateOrder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function FillOrder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function GetAccountStats():Promise<Array<main.GenericInfo>>;

export function GetAddress():Promise<string>;

export function GetAddressBook():Promise<Array<main.AddressInfo>>;

export function GetAllAssets():Promise<Array<main.AssetInfo>>;

export function GetBalance():Promise<Array<main.BalanceInfo>>;

export function GetChainID():Promise<string>;

export function GetFaucetSolutions():Promise<main.FaucetSolutions>;

export function GetLatestBlocks():Promise<Array<main.BlockInfo>>;

export function GetMyAssets():Promise<Array<main.AssetInfo>>;

export function GetOrders(arg1:string):Promise<Array<main.Order>>;

export function GetTransactionStats():Promise<Array<main.GenericInfo>>;

export function GetTransactions():Promise<main.Transactions>;

export function GetUnitPrices():Promise<Array<main.GenericInfo>>;

export function MintAsset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartFaucetSearch():Promise<main.FaucetSearchInfo>;

export function Transfer(arg1:string,arg2:string,arg3:string):Promise<void>;
