// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function GetAccountStats() {
  return window['go']['main']['App']['GetAccountStats']();
}

export function GetAddress() {
  return window['go']['main']['App']['GetAddress']();
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetBalance(arg1) {
  return window['go']['main']['App']['GetBalance'](arg1);
}

export function GetChainID() {
  return window['go']['main']['App']['GetChainID']();
}

export function GetLatestBlocks() {
  return window['go']['main']['App']['GetLatestBlocks']();
}

export function GetTransactionStats() {
  return window['go']['main']['App']['GetTransactionStats']();
}

export function GetUnitPrices() {
  return window['go']['main']['App']['GetUnitPrices']();
}
