// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAsset'](arg1, arg2, arg3);
}

export function GetAccountStats() {
  return window['go']['main']['App']['GetAccountStats']();
}

export function GetAddress() {
  return window['go']['main']['App']['GetAddress']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetChainID() {
  return window['go']['main']['App']['GetChainID']();
}

export function GetLatestBlocks() {
  return window['go']['main']['App']['GetLatestBlocks']();
}

export function GetMyAssets() {
  return window['go']['main']['App']['GetMyAssets']();
}

export function GetTransactionStats() {
  return window['go']['main']['App']['GetTransactionStats']();
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}

export function GetUnitPrices() {
  return window['go']['main']['App']['GetUnitPrices']();
}

export function MintAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['MintAsset'](arg1, arg2, arg3);
}
