[package]
name = "wasmlanche_sdk"
version = "0.1.0"
edition = "2021"
overflow-checks = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.46"
serde = "1.0.185"
serde_json = "1.0.105"
serde_bytes = "0.11.12"
serde_derive = "1.0.185"
[lib]
