// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.15.0
// source: auth.go

package chaintest

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__TestAuth__NumComputeUnits__tag = "\x08" // canoto.Tag(1, canoto.Varint)
	canoto__TestAuth__ActorAddress__tag    = "\x12" // canoto.Tag(2, canoto.Len)
	canoto__TestAuth__SponsorAddress__tag  = "\x1a" // canoto.Tag(3, canoto.Len)
	canoto__TestAuth__ShouldErr__tag       = "\x20" // canoto.Tag(4, canoto.Varint)
	canoto__TestAuth__Start__tag           = "\x28" // canoto.Tag(5, canoto.Varint)
	canoto__TestAuth__End__tag             = "\x30" // canoto.Tag(6, canoto.Varint)
)

type canotoData_TestAuth struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*TestAuth) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero TestAuth
	s := &canoto.Spec{
		Name: "TestAuth",
		Fields: []canoto.FieldType{
			{
				FieldNumber: 1,
				Name:        "NumComputeUnits",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.NumComputeUnits),
			},
			{
				FieldNumber:    2,
				Name:           "ActorAddress",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.ActorAddress)),
			},
			{
				FieldNumber:    3,
				Name:           "SponsorAddress",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.SponsorAddress)),
			},
			{
				FieldNumber: 4,
				Name:        "ShouldErr",
				OneOf:       "",
				TypeBool:    true,
			},
			{
				FieldNumber: 5,
				Name:        "Start",
				OneOf:       "",
				TypeInt:     canoto.SizeOf(zero.Start),
			},
			{
				FieldNumber: 6,
				Name:        "End",
				OneOf:       "",
				TypeInt:     canoto.SizeOf(zero.End),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*TestAuth) MakeCanoto() *TestAuth {
	return new(TestAuth)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *TestAuth) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *TestAuth) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = TestAuth{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.NumComputeUnits); err != nil {
				return err
			}
			if canoto.IsZero(c.NumComputeUnits) {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.ActorAddress)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.ActorAddress)[:], r.B)
			if canoto.IsZero(c.ActorAddress) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 3:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.SponsorAddress)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.SponsorAddress)[:], r.B)
			if canoto.IsZero(c.SponsorAddress) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 4:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBool(&r, &c.ShouldErr); err != nil {
				return err
			}
			if canoto.IsZero(c.ShouldErr) {
				return canoto.ErrZeroValue
			}
		case 5:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadInt(&r, &c.Start); err != nil {
				return err
			}
			if canoto.IsZero(c.Start) {
				return canoto.ErrZeroValue
			}
		case 6:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadInt(&r, &c.End); err != nil {
				return err
			}
			if canoto.IsZero(c.End) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *TestAuth) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *TestAuth) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.NumComputeUnits) {
		size += uint64(len(canoto__TestAuth__NumComputeUnits__tag)) + canoto.SizeUint(c.NumComputeUnits)
	}
	if !canoto.IsZero(c.ActorAddress) {
		size += uint64(len(canoto__TestAuth__ActorAddress__tag)) + canoto.SizeBytes((&c.ActorAddress)[:])
	}
	if !canoto.IsZero(c.SponsorAddress) {
		size += uint64(len(canoto__TestAuth__SponsorAddress__tag)) + canoto.SizeBytes((&c.SponsorAddress)[:])
	}
	if !canoto.IsZero(c.ShouldErr) {
		size += uint64(len(canoto__TestAuth__ShouldErr__tag)) + canoto.SizeBool
	}
	if !canoto.IsZero(c.Start) {
		size += uint64(len(canoto__TestAuth__Start__tag)) + canoto.SizeInt(c.Start)
	}
	if !canoto.IsZero(c.End) {
		size += uint64(len(canoto__TestAuth__End__tag)) + canoto.SizeInt(c.End)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *TestAuth) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TestAuth) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TestAuth) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.NumComputeUnits) {
		canoto.Append(&w, canoto__TestAuth__NumComputeUnits__tag)
		canoto.AppendUint(&w, c.NumComputeUnits)
	}
	if !canoto.IsZero(c.ActorAddress) {
		canoto.Append(&w, canoto__TestAuth__ActorAddress__tag)
		canoto.AppendBytes(&w, (&c.ActorAddress)[:])
	}
	if !canoto.IsZero(c.SponsorAddress) {
		canoto.Append(&w, canoto__TestAuth__SponsorAddress__tag)
		canoto.AppendBytes(&w, (&c.SponsorAddress)[:])
	}
	if !canoto.IsZero(c.ShouldErr) {
		canoto.Append(&w, canoto__TestAuth__ShouldErr__tag)
		canoto.AppendBool(&w, true)
	}
	if !canoto.IsZero(c.Start) {
		canoto.Append(&w, canoto__TestAuth__Start__tag)
		canoto.AppendInt(&w, c.Start)
	}
	if !canoto.IsZero(c.End) {
		canoto.Append(&w, canoto__TestAuth__End__tag)
		canoto.AppendInt(&w, c.End)
	}
	return w
}
