// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.10.0
// source: chain/chaintest/auth.go

package chaintest

import (
	"io"
	"sync/atomic"
	"unicode/utf8"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Int64

	_ = io.ErrUnexpectedEOF
	_ = utf8.ValidString
)

const (
	canoto__TestAuth__NumComputeUnits__tag = "\x09" // canoto.Tag(1, canoto.I64)
	canoto__TestAuth__ActorAddress__tag    = "\x12" // canoto.Tag(2, canoto.Len)
	canoto__TestAuth__SponsorAddress__tag  = "\x1a" // canoto.Tag(3, canoto.Len)
	canoto__TestAuth__ShouldErr__tag       = "\x20" // canoto.Tag(4, canoto.Varint)
	canoto__TestAuth__Start__tag           = "\x28" // canoto.Tag(5, canoto.Varint)
	canoto__TestAuth__End__tag             = "\x30" // canoto.Tag(6, canoto.Varint)
)

type canotoData_TestAuth struct {
	// Enforce noCopy before atomic usage.
	// See https://github.com/StephenButtolph/canoto/pull/32
	_ atomic.Int64

	size int
}

// MakeCanoto creates a new empty value.
func (*TestAuth) MakeCanoto() *TestAuth {
	return new(TestAuth)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
func (c *TestAuth) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// OneOf fields are cached during the unmarshaling process.
//
// The struct is not cleared before unmarshaling, any fields not present in the
// bytes will retain their previous values. If a OneOf field was previously
// cached as being set, attempting to unmarshal that OneOf again will return
// canoto.ErrDuplicateOneOf.
//
// This function enables configuration of reader options.
func (c *TestAuth) UnmarshalCanotoFrom(r canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.I64 {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadFint64(&r, &c.NumComputeUnits); err != nil {
				return err
			}
			if canoto.IsZero(c.NumComputeUnits) {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			var length int64
			if err := canoto.ReadInt(&r, &length); err != nil {
				return err
			}

			const (
				expectedLength      = len(c.ActorAddress)
				expectedLengthInt64 = int64(expectedLength)
			)
			if length != expectedLengthInt64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy(c.ActorAddress[:], r.B)
			if canoto.IsZero(c.ActorAddress) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 3:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			var length int64
			if err := canoto.ReadInt(&r, &length); err != nil {
				return err
			}

			const (
				expectedLength      = len(c.SponsorAddress)
				expectedLengthInt64 = int64(expectedLength)
			)
			if length != expectedLengthInt64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy(c.SponsorAddress[:], r.B)
			if canoto.IsZero(c.SponsorAddress) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 4:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBool(&r, &c.ShouldErr); err != nil {
				return err
			}
			if canoto.IsZero(c.ShouldErr) {
				return canoto.ErrZeroValue
			}
		case 5:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadSint(&r, &c.Start); err != nil {
				return err
			}
			if canoto.IsZero(c.Start) {
				return canoto.ErrZeroValue
			}
		case 6:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadSint(&r, &c.End); err != nil {
				return err
			}
			if canoto.IsZero(c.End) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *TestAuth) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to call this function concurrently.
func (c *TestAuth) CalculateCanotoCache() {
	if c == nil {
		return
	}
	c.canotoData.size = 0
	if !canoto.IsZero(c.NumComputeUnits) {
		c.canotoData.size += len(canoto__TestAuth__NumComputeUnits__tag) + canoto.SizeFint64
	}
	if !canoto.IsZero(c.ActorAddress) {
		c.canotoData.size += len(canoto__TestAuth__ActorAddress__tag) + canoto.SizeBytes(c.ActorAddress[:])
	}
	if !canoto.IsZero(c.SponsorAddress) {
		c.canotoData.size += len(canoto__TestAuth__SponsorAddress__tag) + canoto.SizeBytes(c.SponsorAddress[:])
	}
	if !canoto.IsZero(c.ShouldErr) {
		c.canotoData.size += len(canoto__TestAuth__ShouldErr__tag) + canoto.SizeBool
	}
	if !canoto.IsZero(c.Start) {
		c.canotoData.size += len(canoto__TestAuth__Start__tag) + canoto.SizeSint(c.Start)
	}
	if !canoto.IsZero(c.End) {
		c.canotoData.size += len(canoto__TestAuth__End__tag) + canoto.SizeSint(c.End)
	}
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *TestAuth) CachedCanotoSize() int {
	if c == nil {
		return 0
	}
	return c.canotoData.size
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *TestAuth) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to call this function concurrently.
func (c *TestAuth) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.NumComputeUnits) {
		canoto.Append(&w, canoto__TestAuth__NumComputeUnits__tag)
		canoto.AppendFint64(&w, c.NumComputeUnits)
	}
	if !canoto.IsZero(c.ActorAddress) {
		canoto.Append(&w, canoto__TestAuth__ActorAddress__tag)
		canoto.AppendBytes(&w, c.ActorAddress[:])
	}
	if !canoto.IsZero(c.SponsorAddress) {
		canoto.Append(&w, canoto__TestAuth__SponsorAddress__tag)
		canoto.AppendBytes(&w, c.SponsorAddress[:])
	}
	if !canoto.IsZero(c.ShouldErr) {
		canoto.Append(&w, canoto__TestAuth__ShouldErr__tag)
		canoto.AppendBool(&w, true)
	}
	if !canoto.IsZero(c.Start) {
		canoto.Append(&w, canoto__TestAuth__Start__tag)
		canoto.AppendSint(&w, c.Start)
	}
	if !canoto.IsZero(c.End) {
		canoto.Append(&w, canoto__TestAuth__End__tag)
		canoto.AppendSint(&w, c.End)
	}
	return w
}
