// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.15.0
// source: canoto_parser.go

package codec

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__TypedStruct__Name__tag = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__TypedStruct__ID__tag   = "\x10" // canoto.Tag(2, canoto.Varint)
)

type canotoData_TypedStruct struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*TypedStruct) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero TypedStruct
	s := &canoto.Spec{
		Name: "TypedStruct",
		Fields: []canoto.FieldType{
			{
				FieldNumber: 1,
				Name:        "Name",
				OneOf:       "",
				TypeString:  true,
			},
			{
				FieldNumber: 2,
				Name:        "ID",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.ID),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*TypedStruct) MakeCanoto() *TypedStruct {
	return new(TypedStruct)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *TypedStruct) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *TypedStruct) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = TypedStruct{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadString(&r, &c.Name); err != nil {
				return err
			}
			if len(c.Name) == 0 {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.ID); err != nil {
				return err
			}
			if canoto.IsZero(c.ID) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *TypedStruct) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !canoto.ValidString(c.Name) {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *TypedStruct) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.Name) != 0 {
		size += uint64(len(canoto__TypedStruct__Name__tag)) + canoto.SizeBytes(c.Name)
	}
	if !canoto.IsZero(c.ID) {
		size += uint64(len(canoto__TypedStruct__ID__tag)) + canoto.SizeUint(c.ID)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *TypedStruct) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TypedStruct) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TypedStruct) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.Name) != 0 {
		canoto.Append(&w, canoto__TypedStruct__Name__tag)
		canoto.AppendBytes(&w, c.Name)
	}
	if !canoto.IsZero(c.ID) {
		canoto.Append(&w, canoto__TypedStruct__ID__tag)
		canoto.AppendUint(&w, c.ID)
	}
	return w
}
