# Copyright (C) 2024, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        packages:
          deny:
            - pkg: github.com/stretchr/testify/assert
              desc: github.com/stretchr/testify/require should be used instead.
            - pkg: io/ioutil
              desc: io/ioutil is deprecated. Use package io or os instead.
            - pkg: github.com/ava-labs/hypersdk/internal
              desc: internal packages should not be used in example VMs.
    errorlint:
      # Check for plain type assertions and type switches.
      asserts: false
      # Check for plain error comparisons.
      comparison: false
    gosec:
      excludes:
        - G107 # https://securego.io/docs/rules/g107.html
        - G115 # TODO Enable this ruleset in a follow-up PR
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#bool-literal-in-expr
        - name: bool-literal-in-expr
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return
        - name: early-return
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
        - name: empty-lines
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#struct-tag
        - name: struct-tag
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-naming
        - name: unexported-naming
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unhandled-error
        - name: unhandled-error
          arguments:
            - fmt.Fprint
            - fmt.Fprintf
            - fmt.Print
            - fmt.Printf
            - fmt.Println
            - rand.Read
            - sb.WriteString
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
        - name: unused-receiver
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#useless-break
        - name: useless-break
          disabled: false
    staticcheck:
      # https://staticcheck.io/docs/options#checks
      checks:
        - all
        - -SA1019 # deprecated packages e.g., golang.org/x/crypto/ripemd160
        - -SA6002 # argument should be pointer-like to avoid allocation, for sync.Pool
        - -QF1008 # omit embedded fields from selector expression
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go$
      - .*mock.*
      - third_party$
      - builtin$
      - examples$
issues:
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*mock.*
      - third_party$
      - builtin$
      - examples$
