version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        packages:
          deny:
            - pkg: github.com/stretchr/testify/assert
              desc: github.com/stretchr/testify/require should be used instead.
            - pkg: io/ioutil
              desc: io/ioutil is deprecated. Use package io or os instead.
            - pkg: github.com/ava-labs/hypersdk/internal
              desc: internal packages should not be used in example VMs.
    errorlint:
      asserts: false
      comparison: false
    gosec:
      excludes:
        - G107
        - G115
    revive:
      rules:
        - name: bool-literal-in-expr
          disabled: false
        - name: early-return
          disabled: false
        - name: empty-lines
          disabled: false
        - name: struct-tag
          disabled: false
        - name: unexported-naming
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Fprint
            - fmt.Fprintf
            - fmt.Print
            - fmt.Printf
            - fmt.Println
            - rand.Read
            - sb.WriteString
          disabled: false
        - name: unused-parameter
          disabled: false
        - name: unused-receiver
          disabled: false
        - name: useless-break
          disabled: false
    staticcheck:
      checks:
        - all
        - "-SA1019"
        - "-SA6002"
        - "-QF1008"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go$
      - .*mock.*
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*mock.*
      - third_party$
      - builtin$
      - examples$
