# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

# ref. https://goreleaser.com/customization/build/
builds:
  - id: morpheus-cli
    main: ./cmd/morpheus-cli
    binary: morpheus-cli
    flags:
      - -v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O -D__BLST_PORTABLE__ # Set the CGO flags to use the portable version of BLST
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CC=o64-clang
  - id: morpheusvm
    main: ./cmd/morpheusvm
    binary: morpheusvm
    flags:
      - -v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O -D__BLST_PORTABLE__ # Set the CGO flags to use the portable version of BLST
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CC=o64-clang

checksum:
  name_template: "morpheusvm_checksums.txt"

archives:
  - id: default
    name_template: 'morpheusvm_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
  make_latest: false # Should be done manually
  mode: 'keep-existing' # Should not override releases
  github:
    owner: ava-labs
    name: hypersdk
