{
 "title": "Vryx PoC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transactions Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(avalanche_${ChainID}_vm_hypersdk_vm_txs_included[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Engine Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_vm_hypersdk_chain_engine_backlog",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Transaction Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_vm_hypersdk_chain_rpc_tx_backlog",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Built Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(avalanche_${ChainID}_vm_hypersdk_chain_chunk_build_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(avalanche_${ChainID}_vm_hypersdk_vm_txs_invalid[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(avalanche_${ChainID}_vm_hypersdk_chain_state_changes[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Data Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(avalanche_${ChainID}_vm_hypersdk_chain_units_executed_bandwidth[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executable Transactions (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Collect Chunk Signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_vm_hypersdk_chain_mempool_len",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Txs in Mempool After Build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(avalanche_${ChainID}_vm_hypersdk_chain_remaining_mempool[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_blks_processing",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Root Generate + Commit (Subset of Block Execution)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Last Accepted Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_blks_accepted_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Accepted Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_vm_hypersdk_chain_last_accepted_epoch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Executed Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_vm_hypersdk_chain_last_executed_epoch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Data Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_${ChainID}_vm_hypersdk_chain_data_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job=~\"avalanchego-machine\"} - node_memory_MemFree_bytes{job=~\"avalanchego-machine\"} - node_memory_Buffers_bytes{job=~\"avalanchego-machine\"} - node_memory_Cached_bytes{job=~\"avalanchego-machine\"}) / node_memory_MemTotal_bytes{job=~\"avalanchego-machine\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanchego-machine\", mode=\"idle\"}[30s])) by (instance)) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Network I/O (Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[30s])",
     "legendFormat": "Receive {{device}}"
    }
   ]
  },
  {
   "title": "Network I/O (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\"}[30s])",
     "legendFormat": "Receive {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O (Read)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[30s])",
     "legendFormat": "Read {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O (Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[30s])",
     "legendFormat": "Read {{device}}"
    }
   ]
  }
 ]
}