# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: HyperSDK Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hypersdk-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
      - name: Run static analysis tests
        shell: bash
        run: scripts/tests.lint.sh
      - name: Run shellcheck
        shell: bash
        run: scripts/tests.shellcheck.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
