# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: MorpheusVM Sync Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled,synchronize,reopened]

jobs:
  morpheusvm-sync-tests:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run sync') }}
    runs-on:
      labels: ubuntu-20.04-32
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
          cache-dependency-path: |
            go.sum
            examples/morpheusvm/go.sum
      - name: Run sync tests
        working-directory: ./examples/morpheusvm
        shell: bash
        run: scripts/run.sh
        env:
          MODE: "full-test"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
