# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: MorpheusVM Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  morpheusvm-lint:
    runs-on:
      labels: ubuntu-20.04-32
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
          cache-dependency-path: |
            go.sum
            examples/morpheusvm/go.sum
      - name: Run static analysis tests
        working-directory: ./examples/morpheusvm
        shell: bash
        run: scripts/tests.lint.sh
      - name: Build vm, cli
        working-directory: ./examples/morpheusvm
        shell: bash
        run: scripts/build.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
