# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: Program Simulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  simulator-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Run token simulator test
        working-directory: ./x/programs/rust/examples/token
        shell: bash
        run: scripts/tests.simulator.sh
        env:
          MODE: "full-test"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
