# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: Rust Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static_analysis:
    name: rust-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true

      - name: Check Rust version
        run: rustc --version

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run static analysis tests
        shell: bash
        run: scripts/rust/tests.lint.sh
