# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run static analysis tests
        run: cargo fmt --all --check

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features --document-private-items --all

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run static analysis tests
        shell: bash
        run: cargo clippy --all --all-features --tests --benches --examples -- -D warnings

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run unit tests
        run: cargo test --all-features --all

  simulator-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
          cache: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run token simulator test
        working-directory: ./x/programs/rust/examples/token
        shell: bash
        run: scripts/tests.simulator.sh
        env:
          MODE: 'full-test'
