# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: Simulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  simulator-tests:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run all ci') }}
    runs-on:
      labels: ubuntu-20.04-32
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
          cache-dependency-path: |
            go.sum
            x/programs
      - name: Run token simulator test
        working-directory: ./x/programs/rust/examples/token
        shell: bash
        run: scripts/tests.simulator.sh
        env:
          MODE: "full-test"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
