name: go.mod Checker
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go_mod_tidy:
    name: Tidy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - shell: bash
        run: go mod tidy
      - shell: bash
        working-directory: ./examples/morpheusvm
        run: go mod tidy
      - shell: bash
        working-directory: ./examples/tokenvm
        run: go mod tidy
      - shell: bash
        run: scripts/tests.clean.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
