name: TODO issue bot
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - uses: actions/checkout@v4
    - name: Run tdg-github-action
      uses: ribtoks/tdg-github-action@7e41dea
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
        REF: ${{ github.ref }}
