# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: TokenVM Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tokenvm-lint:
    runs-on:
      labels: ubuntu-20.04-32
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
          cache-dependency-path: |
            go.sum
            examples/tokenvm/go.sum
      - name: Run static analysis tests
        working-directory: ./examples/tokenvm
        shell: bash
        run: scripts/tests.lint.sh
      - name: Build vm, cli, faucet, feed
        working-directory: ./examples/tokenvm
        shell: bash
        run: scripts/build.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
