// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.15.0
// source: abi.go

package abi

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__ABI__ActionsSpec__tag = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__ABI__OutputsSpec__tag = "\x12" // canoto.Tag(2, canoto.Len)
	canoto__ABI__ActionTypes__tag = "\x1a" // canoto.Tag(3, canoto.Len)
	canoto__ABI__OutputTypes__tag = "\x22" // canoto.Tag(4, canoto.Len)
)

type canotoData_ABI struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*ABI) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(ABI{}))
	var zero ABI
	s := &canoto.Spec{
		Name: "ABI",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntry(zero.ActionsSpec)),
				/*FieldNumber:   */ 1,
				/*Name:          */ "ActionsSpec",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntry(zero.OutputsSpec)),
				/*FieldNumber:   */ 2,
				/*Name:          */ "OutputsSpec",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.ActionTypes)),
				/*FieldNumber:   */ 3,
				/*Name:          */ "ActionTypes",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.OutputTypes)),
				/*FieldNumber:   */ 4,
				/*Name:          */ "OutputTypes",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*ABI) MakeCanoto() *ABI {
	return new(ABI)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *ABI) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *ABI) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = ABI{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__ABI__ActionsSpec__tag)
			if err != nil {
				return err
			}

			c.ActionsSpec = canoto.MakeSlice(c.ActionsSpec, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				c.ActionsSpec[0] = canoto.MakePointer(c.ActionsSpec[0])
				if err := (c.ActionsSpec[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__ABI__ActionsSpec__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				c.ActionsSpec[1+i] = canoto.MakePointer(c.ActionsSpec[1+i])
				if err := (c.ActionsSpec[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__ABI__OutputsSpec__tag)
			if err != nil {
				return err
			}

			c.OutputsSpec = canoto.MakeSlice(c.OutputsSpec, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				c.OutputsSpec[0] = canoto.MakePointer(c.OutputsSpec[0])
				if err := (c.OutputsSpec[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__ABI__OutputsSpec__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				c.OutputsSpec[1+i] = canoto.MakePointer(c.OutputsSpec[1+i])
				if err := (c.OutputsSpec[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		case 3:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__ABI__ActionTypes__tag)
			if err != nil {
				return err
			}

			c.ActionTypes = canoto.MakeSlice(c.ActionTypes, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&c.ActionTypes[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__ABI__ActionTypes__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&c.ActionTypes[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		case 4:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__ABI__OutputTypes__tag)
			if err != nil {
				return err
			}

			c.OutputTypes = canoto.MakeSlice(c.OutputTypes, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&c.OutputTypes[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__ABI__OutputTypes__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&c.OutputTypes[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *ABI) ValidCanoto() bool {
	if c == nil {
		return true
	}
	for i := range c.ActionsSpec {
		if c.ActionsSpec[i] != nil && !(c.ActionsSpec[i]).ValidCanoto() {
			return false
		}
	}
	for i := range c.OutputsSpec {
		if c.OutputsSpec[i] != nil && !(c.OutputsSpec[i]).ValidCanoto() {
			return false
		}
	}
	for i := range c.ActionTypes {
		if !(&c.ActionTypes[i]).ValidCanoto() {
			return false
		}
	}
	for i := range c.OutputTypes {
		if !(&c.OutputTypes[i]).ValidCanoto() {
			return false
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *ABI) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	for i := range c.ActionsSpec {
		var fieldSize uint64
		if c.ActionsSpec[i] != nil {
			(c.ActionsSpec[i]).CalculateCanotoCache()
			fieldSize = (c.ActionsSpec[i]).CachedCanotoSize()
		}
		size += uint64(len(canoto__ABI__ActionsSpec__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	for i := range c.OutputsSpec {
		var fieldSize uint64
		if c.OutputsSpec[i] != nil {
			(c.OutputsSpec[i]).CalculateCanotoCache()
			fieldSize = (c.OutputsSpec[i]).CachedCanotoSize()
		}
		size += uint64(len(canoto__ABI__OutputsSpec__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	for i := range c.ActionTypes {
		(&c.ActionTypes[i]).CalculateCanotoCache()
		fieldSize := (&c.ActionTypes[i]).CachedCanotoSize()
		size += uint64(len(canoto__ABI__ActionTypes__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	for i := range c.OutputTypes {
		(&c.OutputTypes[i]).CalculateCanotoCache()
		fieldSize := (&c.OutputTypes[i]).CachedCanotoSize()
		size += uint64(len(canoto__ABI__OutputTypes__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *ABI) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *ABI) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *ABI) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	for i := range c.ActionsSpec {
		canoto.Append(&w, canoto__ABI__ActionsSpec__tag)
		var fieldSize uint64
		if c.ActionsSpec[i] != nil {
			fieldSize = (c.ActionsSpec[i]).CachedCanotoSize()
		}
		canoto.AppendUint(&w, fieldSize)
		if fieldSize != 0 {
			w = (c.ActionsSpec[i]).MarshalCanotoInto(w)
		}
	}
	for i := range c.OutputsSpec {
		canoto.Append(&w, canoto__ABI__OutputsSpec__tag)
		var fieldSize uint64
		if c.OutputsSpec[i] != nil {
			fieldSize = (c.OutputsSpec[i]).CachedCanotoSize()
		}
		canoto.AppendUint(&w, fieldSize)
		if fieldSize != 0 {
			w = (c.OutputsSpec[i]).MarshalCanotoInto(w)
		}
	}
	for i := range c.ActionTypes {
		canoto.Append(&w, canoto__ABI__ActionTypes__tag)
		canoto.AppendUint(&w, (&c.ActionTypes[i]).CachedCanotoSize())
		w = (&c.ActionTypes[i]).MarshalCanotoInto(w)
	}
	for i := range c.OutputTypes {
		canoto.Append(&w, canoto__ABI__OutputTypes__tag)
		canoto.AppendUint(&w, (&c.OutputTypes[i]).CachedCanotoSize())
		w = (&c.OutputTypes[i]).MarshalCanotoInto(w)
	}
	return w
}
